services:
  stack_api:
    build:
      context: .
    ports:
      - 3000:3000
    networks:
      - subnet_1
    env_file:
      - .env
    environment:
      - CACHE_REDIS_HOST=redis
      - DATABASE_POSTGRES_HOST=dbpg
    depends_on:
      - dbpg
      - redis

  dbpg:
    build:
      context: ./docker/postgresql
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - subnet_1

  redis:
    build:
      context: ./docker/redis
    ports:
      - "6379:6379"
    networks:
      - subnet_1

networks:
  subnet_1:
